config/routes.rb
Rails.application.routes.draw do
  get 'auth/google_oauth2/callback', to: 'auth#google_oauth2_callback'
  get 'calendars/create_calendar', to: 'calendars#create_calendar'
  root 'pages#dashboard'
  #get 'pages/dashboard'
  get 'admin', to: 'pages#admin'
  get 'admin/tally', to: 'pages#tally'
  get 'attendance', to: 'pages#attendance'
  post 'attendance', to: 'calendars#record'
  get 'wage_settings', to: 'wage_settings#edit'
  #get 'wage_settings/update'
  resources :employees
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/pages/admin.html.erb
<h1>管理者ページ</h1>

<div class="main-page">
  <div class="main-content">
    <ul>
      <%= link_to '従業員一覧', employees_path %>
      <%= link_to '集計', '/admin/tally' %>
    </ul>
  </div>
  </p>
  <%= link_to 'Back', root_path %>
</div>

app/views/pages/attendance.html.erb
<h1>打刻ページ</h1>

<div class="main-page">
  <div class="main-content" align="center">
<%= form_tag(attendance_path, method: :post) do %>
  <%= select_tag :employee_id, options_for_select(@employees.map { |employee| [employee.name, employee.id] }), class: "pulldown-lg" %>
  </p>
  <%= submit_tag "出勤", class: "btn-in-lg", disabled: @employees.empty? %>
  <%= submit_tag "退勤", class: "btn-out-lg", disabled: @employees.empty? || @disabled.map{|e| puts '++++++++++++++++++++++++++++++++++++++++++'; puts :employee_id; false}[0] || @disabled[:employee_id] %>
<% end %>
  </div>
  </p>
  <%= link_to 'Back', root_path %>
</div>

app/views/pages/dashboard.html.erb
<h1>ShiftCal</h1>

<div class="main-page">
  <div class="main-content">
    <%= link_to '打刻する', attendance_path %>
    <% #if current_user.admin? %>
    <%= link_to '管理者用ページ', admin_path %>
    <% #end %>
  </div>
  <a href="https://github.com/kimura3104/ShiftCal#shiftcal">ヘルプ</a>
</div>

app/views/pages/tally.html.erb
<h1>勤怠集計ページ</h1>


<div class="main-page">
  <div class="main-content">
  <%= form_with url: '/admin/tally', method: :get, local: true do |f| %>
  <label>月を選択</label>
  <%= raw sprintf(f.date_select(
    :date,
    start_year: (Time.now.year - 1),
    end_year: (Time.now.year + 1),
    default: DateTime.new(@year.to_i, @month.to_i, 1) || Time.now,
    use_month_numbers: true,
    discard_day: true,
    date_separator:'%s'
    ),"年") + "月"
     %>
  <%= f.submit '絞り込み', class: 'btn btn-primary' %>
<% end %>
<label>従業員を選択</label>
<%= form_tag(admin_tally_path, method: :get) do %>
  <%= select_tag(:employee_id, options_from_collection_for_select(Employee.all, :id, :name, params[:employee_id]), include_blank: true) %>
  <%= submit_tag("絞り込み") %>
<% end %>

<table>
  <thead>
    <tr>
      <th>従業員名</th>
      <th>出勤日数</th>
      <th>勤務時間</th>
      <th>賃金（円）</th>
    </tr>
  </thead>
  <tbody>
    <% if @employee %>
      <tr>
        <td><%= @employee.name %></td>
        <td><%= @attendance_counts[@employee.id] || 0 %></td>
        <td><%= "#{@attendance_minutes[@employee.id].to_i/60}時間#{@attendance_minutes[@employee.id].to_i%60}分" || 0 %></td>
        <td><%= @attendance_wage[@employee.id] || 0 %></td>
      </tr>
    <% else %>
      <% current_user.employees.each do |employee| %>
        <tr>
          <td><%= employee.name %></td>
          <td><%= @attendance_counts[employee.id] || 0 %></td>
          <td><%= "#{@attendance_minutes[employee.id].to_i/60}時間#{@attendance_minutes[employee.id].to_i%60}分" || 0 %></td>
          <td><%= @attendance_wage[employee.id] || 0 %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<table>
  <thead>
    <tr>
      <th>日付</th>
      <th>従業員名</th>
      <th>出勤時刻</th>
      <th>退勤時刻</th>
      <th>勤務時間</th>
    </tr>
  </thead>
  <tbody>
    <% @attendance_list.each do |record| %>
      <tr>
        <td><%= record["date"] %></td>
        <td><%= record["enployee"] || 0 %></td>
        <td><%= record["start"].strftime('%H:%M') || 0 %></td>
        <td><%= record["end"].strftime('%H:%M') || 0 %></td>
        <td><%= "#{record["minutes"].to_i/60}時間#{record["minutes"].to_i%60}分" || 0 %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  </div>
  </p>
  <%= link_to 'Back', admin_path %>
</div>